jobs:
  build:
    environment: ci
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: '8'
        server-id: ossrh
        server-password: CI_DEPLOY_PASSWORD
        server-username: CI_DEPLOY_USERNAME
    - continue-on-error: true
      name: Build With Maven
      run: mvn -B package --file pom.xml "-Dextend.dingtalk.webhook=${{ secrets.CI_DINGTALK_HOOK
        }}" "-Dextend.dingtalk.secret=${{ secrets.CI_DINGTALK_SECRET }}" -P ci
    - continue-on-error: true
      id: projectVersion
      if: github.event_name != 'pull_request'
      name: Extract project Maven version
      run: echo "version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.3.0:evaluate
        -DforceStdout -Dexpression=revision -q)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      env:
        CI_DEPLOY_PASSWORD: ${{ secrets.HCCAKE_OSSRH_PASSWORD }}
        CI_DEPLOY_USERNAME: ${{ secrets.HCCAKE_OSSRH_USERNAME }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      if: github.event_name != 'pull_request' && endsWith(steps.projectVersion.outputs.version,
        '-SNAPSHOT')
      name: Deploy Snapshot
      run: mvn -B deploy -DskipTests -P ossrh
    - continue-on-error: true
      if: github.event_name != 'pull_request'
      name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
